name: API Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant permission
        run: chmod +x gradlew

      - name: Run API Tests
        run: ./gradlew clean test
        continue-on-error: true
        env:
          DEBUG: ${{ secrets.DEBUG }}
          BASE_URL: ${{ secrets.BASE_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COMPANY_ID: ${{ secrets.COMPANY_ID }}

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Extract Test Results
        if: always()
        run: |
          RESULT_FILE=$(find . -name "testng-results.xml" | head -1)
          PASS_COUNT=$(grep -o 'status="PASS"' $RESULT_FILE | wc -l)
          FAIL_COUNT=$(grep -o 'status="FAIL"' $RESULT_FILE | wc -l)
          FAIL_TESTS=$(grep 'status="FAIL"' $RESULT_FILE | sed -n 's/.*name="\([^"]*\)".*/\1/p' | tr '\n' ', ')
          echo "PASS_COUNT=$PASS_COUNT" >> $GITHUB_ENV
          echo "FAIL_COUNT=$FAIL_COUNT" >> $GITHUB_ENV
          echo "FAIL_TESTS=$FAIL_TESTS" >> $GITHUB_ENV

      - name: Send Telegram Notification
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          REPO="${{ github.repository }}"
          RUN_ID="${{ github.run_id }}"
          REPORT_URL="https://github.com/$REPO/actions/runs/$RUN_ID"

          if [ "$FAIL_COUNT" -gt 0 ]; then
            RESULT_STATUS="FAILED"
          else
            RESULT_STATUS="SUCCESS"
          fi

          MESSAGE="ðŸ“Š API Automation CI Result\n\nResult : $RESULT_STATUS\nPASS : $PASS_COUNT\nFAIL : $FAIL_COUNT\n\nFailed Tests :\n$FAIL_TESTS\n\nReport :\n$REPORT_URL"

          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE"